### PR TITLE
React 15.0 compat

### PR DESCRIPTION
**Pull request by jbinto**

### CODE REVIEW

**Comment by jbinto** [comment]
Tests will continue to fail until we publish a new frig version and point to that in package.json.

**Comment by jbinto** [comment]
Coverage decreased because there are many failing tests.

**Comment by jbinto** [comment]
# switch issue

2 out of the 3 switches in examples aren't working (time of day, the unlabelled one -- red/blue works fine):

screenshot 2016-05-27 11 42 56

``` jsx
          <div className="row">
            <Input
              name="time_of_day"
              type="switch"
              xs={6}
              label="Time of Day"
              handleWidth={100}
              onText="Enabled"
              offText="Disabled"
              errors={['This error is an example', 'As is this one']}
            />
            <Input
              name="time_of_night"
              type="switch"
              xs={6}
              label={false}
            />
            <Input
              name="red_or_blue"
              type="switch"
              onText="Red"
              offText="Blue"
              onValue="red"
              offValue="blue"
            />
          </div>
```

**Comment by jbinto** [comment]
Re: switch issue

Isolated it to switches without an `onValue`/`offValue`.

**Comment by jbinto** [comment]
Re: switch issue

Fixed in https://github.com/frig-js/frig/pull/128/commits/14a9f7d7c9bcd3d04795d38b034298d1f18bbbb1

**Comment by SpiritBreaker226** [comment]
To fix the test, version 0.12.0 of Frig core needs to be published first, as it contains the necessary functions for Frigging Bootstrap components to use.

**Comment by jbinto** [comment]
finally passing tests :+1:

**Pull request merged**
