### PR TITLE
Add ESLint To All Components & Helpers

### PR DESCRIPTION
**Pull request by SpiritBreaker226**
Add ESLint to all components & helpers using the same ESLint rules as Frig, https://github.com/frig-js/frig/pull/45, Add ESLint with airbnb rules, fix all files

### CODE REVIEW

**Comment by jbinto** [comment]
In `src/javascripts/components/file.js` we changed `componentDidMount` to `componentWillMount` due to [react/no-did-mount-set-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md). 

[This will prevent a re-render/render thrashing.](https://facebook.github.io/react/docs/component-specs.html#mounting-componentwillmount) Need to test this.

**Comment by jbinto** [comment]
There were a bunch of places where we are setting `displayName` on the instance rather than the class, which React doesn't do anything with. We should be setting `static displayName`.

(I was wondering why eslint was warning, expecting `displayName` to be below things like `defaultProps` and `propTypes`, but there was nothing special about `displayName` specifically, it was just warning because it was an instance declared "in between" statics.)

**Comment by jbinto** [comment]
`src/javascripts/components/timepicker_popup.js` would benefit greatly from some unit tests and refactoring. Specifically `_setMinutesSinceMidnight` which has a lot of confusing arithmetic. Didn't want to do that in this PR, have to come back to it later.

**Comment by jbinto** [comment]
@SpiritBreaker226 what is `this.f()`? typo?

https://github.com/frig-js/frigging-bootstrap/pull/29/files#diff-21a4e72329a9e9443d13f3a72895b147L131

**Comment by jbinto** [comment]
Just like in https://github.com/frig-js/frig/pull/45, refactored `util.js`, copy-paste follows:

_"Refactored util.js to not have a top-level util object, that gets self-referenced (e.g. util.foo calls util.bar) -- instead just make every util top level and export them directly"_

**Comment by jbinto** [comment]
Otherwise all is well. Look into [this](https://github.com/frig-js/frigging-bootstrap/pull/29#issuecomment-208947203) and I will merge.

**Comment by SpiritBreaker226** [comment]
> what is this.f()? typo?

This was a typo it should have not been touch, this has been fix and push to the pull request

**Comment by SpiritBreaker226** [comment]
> I was wondering why eslint was warning, expecting displayName to be below things like defaultProps and propTypes, but there was nothing special about displayName specifically, it was just warning because it was an instance declared "in between" statics.

To add to @jbinto comment this has to with the fact in ES6 React components are classes in JavaScript. Because of this ESLint treats them as such, so `static` valuables are actually class valuables should always be the first valuables in a class.

**Comment by jbinto** [comment]
Merged.

**Comment by SpiritBreaker226** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;1TLvQlpk&#x2F;1263-frigging-bootstrap-babel-and-eslint"> Frigging BootStrap: babel and eslint</a>

**Pull request merged**
