### PR TITLE
Rewrite Timepicker Component & Add Tests

### PR DESCRIPTION
**Pull request by SpiritBreaker226**

### CODE REVIEW

**Comment by jbinto** [comment]
Begin testing for `<TimePickerPopup>`.

Ran into issues getting the full component tree to render with Enzyme. There is a dependency on `<UnboundInput>`, which in turn has a dependency on the theme, which we're not providing.

We'll ~~merge~~ PR what we have for now and revisit later.

**Comment by jbinto** [comment]
It is likely that with the current design, we won't be able to (or even want to) test `TimePicker` or `TimePickerPopup` entirely in isolation of other components.

Two approaches we could take (we could do both):

1) Refactor all time calculation code out of the React component and into some sort of helper; and unit test that,

2) Write a higher-level integration test using `<Input type="time">` inside a `<Form>` tag, so all necessary context/theme/etc is already implicitly set up

**Comment by SpiritBreaker226** [comment]
Refactor the Time Picker code to be more readable because it has become to complex with having the formula inside its popup. Which will make testing both the TimePicker and popup hard to do.

So the plan for the Time Picker is as follows. Split the time when it comes into the Time Picker, from Frig, and send into a new class called Time Formatter. Where the time will be formatted for the Time Picker Popup to use.

If the user changes the time in the Time Picker Popup the time will be combine and sent back to the Time Formatter, in Time Picker, before sending to the Time Picker and to Frig in general.

**Comment by SpiritBreaker226** [comment]
Refactor the Time Picker code to be more readable because it has become to complex with having the formula inside its popup. Which will make testing both the TimePicker and popup hard to do.

So the plan for the Time Picker is as follows. Split the time when it comes into the Time Picker, from Frig, and send into a new class called Time Formatter. Where the time will be formatted for the Time Picker Popup to use.

If the user changes the time in the Time Picker Popup the time will be combine and sent back to the Time Formatter, in Time Picker, before sending to the Time Picker and to Frig in general.

**Pull request merged**
